### ISSUE TITLE
PROPFIND 405 method not allowed

### ISSUE THREAD

**Issue by marnec** [chonjay21/docker-webdav#4]
My container worked for some months, then I restarted it for a certificates issue and from that moment I get this error

PROPFIND /redacted/ HTTP/1.1" 405 225

this is my compose
```
services:
  webdav:
    image: chonjay21/webdav
    platform: linux/arm64
    environment:
      - APP_USER_NAME=redacted
      - APP_USER_PASSWD=redacted
      - APP_UID=33
      - APP_GID=33
      - APP_UMASK=002
      - TZ=Europe/Rome
    volumes:
      - ./data:/var/webdav
      - ./config:/webdav/config                                 #optional
    networks:
      ssl-network:
        aliases:
          - webdav

networks:
  ssl-network:
    external: true
```

I used UID/GID=33 for problems related to https://github.com/chonjay21/docker-webdav/pull/3
